<a href="https://colab.research.google.com/github/manasathirumalareddy/python_fundamentals/blob/main/class_27%2C28%2C29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# class 27 user input in array search element


In [ ]:
from array import *
arr = array('i',[])
n = int(input("enter the length of array"))
for i in range(n):
  x = int(input("enter the next value"))
  arr.append(x)
print(arr)

enter the length of array4
enter the next value12
enter the next value3
enter the next value8
enter the next value9
array('i', [12, 3, 8, 9])


In [ ]:
from array import *
arr = array('i',[])
n = int(input("enter the length of array"))
for i in range(n):
  x = int(input("enter the next value"))
  arr.append(x)
print(arr)
val = int(input("enter the value for search"))
k = 0
for e in arr:
  if e==val:
    print(k)
    break
  k+=1

enter the length of array4
enter the next value34
enter the next value36
enter the next value87
enter the next value65
array('i', [34, 36, 87, 65])
enter the value for search87
2


In [ ]:
from array import *
arr = array('i',[])
n = int(input("enter the length of array"))
for i in range(n):
  x = int(input("enter the next value"))
  arr.append(x)
print(arr)
val = int(input("enter the value for search"))
k = 0
for e in arr:
  if e==val:
    print(k)
    break
  k+=1
print(arr.index(val))

enter the length of array4
enter the next value234
enter the next value567
enter the next value897
enter the next value654
array('i', [234, 567, 897, 654])
enter the value for search897
2
2


# class 28 numpy
numpy is used to create multidimensional array.from numpy import*

# class 29 ways of creating arrays in numpy(array(),linspace(),logspace(),arange(),zeros(),ones().
function linspace will take 3 parameters start,stop,step.(0,16,10)10 means number of parts divided.break down the value into 10 different parts.if we not mention the value of step it will divide the value into 50 parts by default.
**Arange**
(1,10,2) here 2 means step difference btw the start and stop.
**logspace**
in linspace the gap btw 2 values is fixed.in logspace the difference btw 2 values depend on log value




In [ ]:
from numpy import *
arr = array([2,4,5,7])
print(arr)

[2 4 5 7]


In [ ]:
from numpy import *
arr = linspace(0,15,16)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [ ]:
from numpy import *
arr = linspace(0,15,20)
print(arr)

[ 0.          0.78947368  1.57894737  2.36842105  3.15789474  3.94736842
  4.73684211  5.52631579  6.31578947  7.10526316  7.89473684  8.68421053
  9.47368421 10.26315789 11.05263158 11.84210526 12.63157895 13.42105263
 14.21052632 15.        ]


In [ ]:
from numpy import *
arr = linspace(0,15)
print(arr)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [ ]:
from numpy import *
arr = arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [ ]:
from numpy import *
arr = logspace(1,40,5)
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [ ]:
from numpy import *
arr = logspace(1,40,5)
print('%.2f' %arr[0])

10.00


In [ ]:
from numpy import *
arr = logspace(1,40,5)
print('%.2f' %arr[4])

10000000000000000303786028427003666890752.00


In [ ]:
from numpy import *
arr = zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
from numpy import *
arr = ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [ ]:
from numpy import *
arr = ones(5,int)
print(arr)

[1 1 1 1 1]
