<a href="https://colab.research.google.com/github/manasathirumalareddy/python_fundamentals/blob/main/class_30%2C31.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# class 30 copying a array in python:array addition,aliasing,shallow copy ,deep copy
vectorised operations to add 2 arrays.we can find sin,cos,sqrt,sum,min,max,sort,unique of the array.we can concatenate the values in array that is mixing the values into one array.aliasing happens whenever one variable's value is assigned to another variable.view() is a function used to create a new array the address will be different.shallow copy means it will copy the elements,and both are dependent on each other.deep copy means 2 different arrays and not linked to each other in any way. view means shallow copy,copy means deep copy will be implemented.



In [ ]:
from numpy import *
arr1 = array([1,3,5,6])
print(cos(arr1))


[ 0.54030231 -0.9899925   0.28366219  0.96017029]


In [ ]:
from numpy import *
arr1 = array([1,3,5,6])
print(sqrt(arr1))


[1.         1.73205081 2.23606798 2.44948974]


In [ ]:
from numpy import *
arr1 = array([1,9,3,5,6])
print(sort(arr1))


[1 3 5 6 9]


In [ ]:
from numpy import *
arr1 = array([3,2,6,8,7])
arr2 = array([3,5,7,8,9])
print(concatenate([arr1,arr2]))

[3 2 6 8 7 3 5 7 8 9]


In [ ]:
from numpy import*
arr1 = array([3,5,7,9])
arr2 = arr1
print(arr1)
print(arr2)

[3 5 7 9]
[3 5 7 9]


In [ ]:
from numpy import*
arr1 = array([3,5,7,9])
arr2 = arr1
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[3 5 7 9]
[3 5 7 9]
134911433939760
134911433939760


In [ ]:
from numpy import*
arr1 = array([3,5,7,9])
arr2 = arr1.view()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[3 5 7 9]
[3 5 7 9]
134911433453616
134911433953168


In [ ]:
from numpy import*
arr1 = array([3,5,7,9])
arr2 = arr1.view()
arr1[1] = 4
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[3 4 7 9]
[3 4 7 9]
134911433959600
134911433962864


In [ ]:
from numpy import*
arr1 = array([3,5,7,9])
arr2 = arr1.copy()
arr1[2] = 4
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[3 5 4 9]
[3 5 7 9]
134911433735120
134911434117776


# class 31 working with matrix in python
2D array,n.dim gives dimension of the array.shape gives no.of rows & columns.size gives entire block.flatten will give the 2D array in 1D array.from 1D array we can get 2D array by function reshape.matrices


In [ ]:
from numpy import *
arr1 = array([
                 [2,4,8],
                 [3,6,5]

              ])
arr2 = arr1.flatten()
print(arr2)

[2 4 8 3 6 5]


In [ ]:
from numpy import *
arr1 = array([
                 [2,4,8,6,8,9],
                 [3,6,5,7,9,8]

              ])
arr2 = arr1.flatten()
arr3 = arr2.reshape(3,4)
print(arr3)

[[2 4 8 6]
 [8 9 3 6]
 [5 7 9 8]]


In [ ]:
from numpy import *
arr1 = array([
                 [2,4,8,6,8,9],
                 [3,6,5,7,9,8]

              ])
arr2 = arr1.flatten()
arr3 = arr2.reshape(2,2,3)
print(arr3)

[[[2 4 8]
  [6 8 9]]

 [[3 6 5]
  [7 9 8]]]


In [ ]:
from numpy import *
arr1 = array([
                 [2,4,8,6],
                 [3,6,5,8]


              ])
m = matrix(arr1)

print(m)

[[2 4 8 6]
 [3 6 5 8]]


In [ ]:
from numpy import *
m = matrix('1 2 3 6 ; 4 5 6 7')
print(m)

[[1 2 3 6]
 [4 5 6 7]]


In [ ]:
from numpy import *
m = matrix('1 2; 3 6 ; 4 5; 6 7')
print(m)

[[1 2]
 [3 6]
 [4 5]
 [6 7]]


In [ ]:
from numpy import *
m = matrix('1 2 3 ;6 4 5; 6 7 8')
print(m)

[[1 2 3]
 [6 4 5]
 [6 7 8]]


In [ ]:
from numpy import *
m = matrix('1 2 3 ;6 4 5; 6 7 8')
print(diagonal(m))

[1 4 8]


In [ ]:
from numpy import *
m = matrix('1 2 3 ;6 4 5; 6 7 8')
print(m.min())

1


In [ ]:
from numpy import *
m = matrix('1 2 3 ;6 4 5; 6 7 8')
print(m.max())

8


In [ ]:
from numpy import *
m1 = matrix('1 2 3 ;6 4 5; 6 7 8')
m2 = matrix('2 4 6 ; 4 6 8; 3 5 9')
m3 = m1 + m2

print(m3)

[[ 3  6  9]
 [10 10 13]
 [ 9 12 17]]


In [ ]:
from numpy import *
m1 = matrix('1 2 3 ;6 4 5; 6 7 8')
m2 = matrix('2 4 6 ; 4 6 8; 3 5 9')
m3 = m1 * m2
print(m3)


[[ 19  31  49]
 [ 43  73 113]
 [ 64 106 164]]
